###
GET http://localhost:8080/public
###
GET http://localhost:8080/private
###
POST http://localhost:8080/login
Content-Type: application/json

{
  "username":"hoge",
  "password":"fuga"
}
### ADMIN token発行
POST http://localhost:8080/login
Content-Type: application/json

{
  "username":"root",
  "password":"password"
}
### USER token発行
POST http://localhost:8080/login
Content-Type: application/json

{
  "username":"user",
  "password":"password"
}
###
GET http://localhost:8080/private
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJob2dlIiwiZXhwIjoxNTY1MzMwNjg2fQ.l9VB8SQUDniQUuspeTTZHvFghrBx5c51KqSbDWDBkqbYJivUW97OG5J-irQrDz8iACGEah0prIN0j9wnJou1VQ
###
GET http://localhost:8080/private
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJob2dlIiwiZXhwIjoxNTY1Mjk0MTM1fQ.Wg_9-tdc6Ht43GGB-YS6MHVgbSuVA9pPjxqFx07esb21TXw9Jzj1iqWEZdIfDvR2aWqw3vMzy8F67JIqHGKcog


####################################################
# User
####################################################
### 全件取得
GET http://localhost:8080/users
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJyb290IiwiZXhwIjoxNTY1NDQ5NTg3LCJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOIl19._kEYvOShOygakc_JdQFx6pIfMfP032fA46bVErWnhjr2tyFdGomvX8CIdhVy0VTvGMEzeQYSDK6eKJEF7wCROA

### 全件取得
GET http://localhost:8080/users
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyIiwiZXhwIjoxNTY1NDQ3NDc1LCJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXX0.TAHVH1R9R10DbGLQq-i6oDM1-Qls8oj_i0JPe_gU41p2yvNsVez1Qb3GpIV84KpaPXdPRlC-Qj-ziHMLluY-xg

### ID指定取得
GET http://localhost:8080/users/hoge

### 新規保存
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "fuga",
  "password": "password",
  "enabled": "true",
  "authorities": [
    { "authority": "ADMIN" },
    { "authority": "USER" }
  ]
}

### 更新
PUT http://localhost:8080/users/1
Content-Type: application/json

{
  "title":"hoge",
  "isbn":"1234567890",
  "publicationYear":"2019",
  "pubId":"1"
}

### 削除
DELETE http://localhost:8080/users/hoge
