image: java:8-jdk

stages:
  - test
  - deploy

job 1:
  stage: test
  script:
    - echo test run!
    - sh gradlew test

job 2:
  stage: deploy
  script:
    - echo deploy run!
    - echo $CI_COMMIT_REF_NAME
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APPNAME.git
    - git checkout $CI_COMMIT_REF_NAME
    - git branch -a
    - git remote -v
    - git push heroku $CI_COMMIT_REF_NAME:master
  only:
    - master
