###
GET http://localhost:8080/public
###
GET http://localhost:8080/private
###
POST http://localhost:8080/login
Content-Type: application/json

{
  "username":"hoge",
  "password":"fuga"
}
### ADMIN token発行
POST http://localhost:8080/login
Content-Type: application/json

{ "username":"root", "password":"password" }
### USER token発行
POST http://localhost:8080/login
Content-Type: application/json

{ "username":"user", "password":"password" } 
### GUEST token発行
POST http://localhost:8080/login
Content-Type: application/json

{ "username":"guest", "password":"password" } 
### admin
GET http://localhost:8080/private
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJyb290IiwiZXhwIjoxNTY1NDUwNzU1LCJhdXRob3JpdGllcyI6WyJBRE1JTiJdfQ.rMh0yguNLpPx3qtVpFmFM5l9-Rr4I0xXL7kR6CCsTiwhSuBJLC3b6D8smQuMDMKmQgjSee7RMSu0LC440EdC2w
### user
GET http://localhost:8080/private
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyIiwiZXhwIjoxNTY1NDUxOTA4LCJhdXRob3JpdGllcyI6WyJVU0VSIl19.O_7-SWG2vhmyNWiHO-WqWWXUvLO2VdN1Q7IKtPEv14Mc89qtS3Ujia7SW-TnkND6tJPn5d74i3_Lz0m9ouA9zw


### アドミン
GET http://localhost:8080/useronly
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJyb290IiwiZXhwIjoxNTY1NDUwNzU1LCJhdXRob3JpdGllcyI6WyJBRE1JTiJdfQ.rMh0yguNLpPx3qtVpFmFM5l9-Rr4I0xXL7kR6CCsTiwhSuBJLC3b6D8smQuMDMKmQgjSee7RMSu0LC440EdC2w
### ユーザー
GET http://localhost:8080/useronly
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyIiwiZXhwIjoxNTY1NDUxNDU4LCJhdXRob3JpdGllcyI6WyJVU0VSIl19.JsxQwF6QZnZJLvNL2cCbbtBhQehM10ZFZdrqhFRmx42Cd2os-_RmGTzcap8GM06QKEk1O0dXqB0gen1tk6IFaA

####################################################
# User
####################################################
### 全件取得
GET http://localhost:8080/users
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJyb290IiwiZXhwIjoxNTY1NDUwNzU1LCJhdXRob3JpdGllcyI6WyJBRE1JTiJdfQ.rMh0yguNLpPx3qtVpFmFM5l9-Rr4I0xXL7kR6CCsTiwhSuBJLC3b6D8smQuMDMKmQgjSee7RMSu0LC440EdC2w

### 全件取得
GET http://localhost:8080/users
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyIiwiZXhwIjoxNTY1NDUwNzY3LCJhdXRob3JpdGllcyI6WyJVU0VSIl19.oLuYbvQ7qlK38QoeBQpfnjhoyxBLJAP4Zn-fN_0ByAkPGnz3qD74eT6_8I2GYKAiWrPiiN1F_iBSprt57Quv5w

### ID指定取得
GET http://localhost:8080/users/hoge

### 新規保存
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "fuga",
  "password": "password",
  "enabled": "true",
  "authorities": [
    { "authority": "ADMIN" },
    { "authority": "USER" }
  ]
}

### 更新
PUT http://localhost:8080/users/1
Content-Type: application/json

{
  "title":"hoge",
  "isbn":"1234567890",
  "publicationYear":"2019",
  "pubId":"1"
}

### 削除
DELETE http://localhost:8080/users/hoge
